# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev
  - stable

stages:
  - analyzer_and_format:
    - dartfmt
    # Skipping --fatal-infos  until we can regenerate this package with publish
    # json_serializable
    - dartanalyzer: --fatal-warnings .
  - unit_test:
    # Run the tests -- include the default-skipped presubmit tests
    - test: --run-skipped
