# See https://github.com/dart-lang/mono_repo for details
dart:
- 2.1.1
- dev

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings --fatal-infos .
    dart: [dev]
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings .
    dart: [2.1.1]
- unit_test:
  # Run the tests -- include the default-skipped presubmit tests
  - test: --run-skipped

cache:
  directories:
  - .dart_tool/build
