# See https://github.com/dart-lang/mono_repo for details
dart:
- 2.1.0
- dev

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
    dart: [dev]
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings .
    dart: [2.0.0]
- unit_test:
  # Run the tests -- include the default-skipped presubmit tests
  - test: --run-skipped

cache:
  directories:
  - .dart_tool/build
