name: example
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  json_annotation: ^0.2.2

dev_dependencies:
  build_runner: ^0.6.1
  json_serializable: ^0.3.0

  # Used by tests. Not required to use `json_serializable`.
  path: ^1.5.1
  test: ^0.12.29
