name: example
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.2

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.6

  # Used by tests. Not required to use `json_serializable`.
  build_verify: ^1.0.0
  path: ^1.5.1
  test: ^1.6.0

dependency_overrides:
  json_annotation:
    path: ../json_annotation
  json_serializable:
    path: ../json_serializable     

