name: example
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  json_annotation: ^0.2.5

dev_dependencies:
  build_runner: ^0.8.9
  json_serializable: ^0.5.4

  # Used by tests. Not required to use `json_serializable`.
  path: ^1.5.1
  test: ^0.12.38
