name: example
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  json_annotation: ^0.2.2

dev_dependencies:
  build_runner: ^0.7.6
  json_serializable: ^0.3.1

  # Used by tests. Not required to use `json_serializable`.
  path: ^1.5.1
  test: ^0.12.29
