name: example
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  json_annotation: ^1.0.0

dev_dependencies:
  build_runner: ^0.9.0
  json_serializable: ^1.0.0

  # Used by tests. Not required to use `json_serializable`.
  path: ^1.5.1
  test: ^1.3.0
