name: example
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  json_annotation: ^0.2.1

dev_dependencies:
  build_runner: any
  json_serializable: ^0.2.5
  source_gen: ^0.7.2+1
  test: ^0.12.29

dependency_overrides:
  json_annotation:
    path: ../json_annotation
  json_serializable:
    path: ../json_serializable
