name: example
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  json_annotation: ^0.3.0

dev_dependencies:
  build_runner: ^0.9.0
  json_serializable: ^0.6.0

  # Used by tests. Not required to use `json_serializable`.
  path: ^1.5.1
  test: ^1.3.0

dependency_overrides:
  json_serializable:
    path: ../json_serializable
  json_annotation:
    path: ../json_annotation
  source_gen:
    git:
      url: git@github.com:dart-lang/source_gen.git
      path: source_gen
