# Created with https://github.com/dart-lang/mono_repo
language: dart

# Unpin SDK after https://github.com/dart-lang/sdk/issues/31940
dart:
  - "dev/release/2.0.0-dev.17.0"

env:
  - PKG=example TASK=dartanalyzer
  - PKG=example TASK=dartfmt
  - PKG=example TASK=test
  - PKG=json_annotation TASK=dartanalyzer
  - PKG=json_annotation TASK=dartfmt
  - PKG=json_serializable TASK=dartanalyzer
  - PKG=json_serializable TASK=dartfmt
  - PKG=json_serializable TASK=test

matrix:
  exclude:
    - dart: stable
      env: PKG=example TASK=dartanalyzer
    - dart: stable
      env: PKG=example TASK=dartfmt
    - dart: stable
      env: PKG=json_serializable TASK=dartanalyzer
    - dart: stable
      env: PKG=json_serializable TASK=dartfmt

script: ./tool/travis.sh

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
