# Created with package:mono_repo v1.2.1
language: dart

# Custom configuration
sudo: required
addons:
  chrome: stable
branches:
  only:
    - master

jobs:
  include:
    - stage: analyzer_and_format
      name: "SDK: dev - DIR: example - TASKS: [dartfmt -n --set-exit-if-changed ., dartanalyzer --fatal-infos --fatal-warnings .]"
      script: ./tool/travis.sh dartfmt dartanalyzer_0
      env: PKG="example"
      dart: dev
    - stage: analyzer_and_format_stable
      name: "SDK: stable - DIR: example - TASKS: [dartfmt -n --set-exit-if-changed ., dartanalyzer --fatal-warnings .]"
      script: ./tool/travis.sh dartfmt dartanalyzer_1
      env: PKG="example"
      dart: stable
    - stage: unit_test
      name: "SDK: stable - DIR: example - TASKS: pub run test --run-skipped"
      script: ./tool/travis.sh test_0
      env: PKG="example"
      dart: stable
    - stage: analyzer_and_format_stable
      name: "SDK: stable - DIR: json_annotation - TASKS: [dartfmt -n --set-exit-if-changed ., dartanalyzer --fatal-warnings .]"
      script: ./tool/travis.sh dartfmt dartanalyzer_1
      env: PKG="json_annotation"
      dart: stable
    - stage: analyzer_and_format
      name: "SDK: dev - DIR: json_serializable - TASKS: [dartfmt -n --set-exit-if-changed ., dartanalyzer --fatal-infos --fatal-warnings .]"
      script: ./tool/travis.sh dartfmt dartanalyzer_0
      env: PKG="json_serializable"
      dart: dev
    - stage: analyzer_and_format_stable
      name: "SDK: stable - DIR: json_serializable - TASKS: [dartfmt -n --set-exit-if-changed ., dartanalyzer --fatal-warnings .]"
      script: ./tool/travis.sh dartfmt dartanalyzer_1
      env: PKG="json_serializable"
      dart: stable
    - stage: unit_test
      name: "SDK: stable - DIR: json_serializable - TASKS: pub run test"
      script: ./tool/travis.sh test_1
      env: PKG="json_serializable"
      dart: stable
    - stage: unit_test
      name: "SDK: 2.0.0 - DIR: json_serializable - TASKS: pub run test"
      script: ./tool/travis.sh test_1
      env: PKG="json_serializable"
      dart: "2.0.0"
    - stage: unit_test
      name: "SDK: dev - DIR: json_serializable - TASKS: pub run test"
      script: ./tool/travis.sh test_1
      env: PKG="json_serializable"
      dart: dev
    - stage: unit_test
      name: "SDK: stable - DIR: json_serializable - TASKS: pub run test --run-skipped test/ensure_build_test.dart"
      script: ./tool/travis.sh test_2
      env: PKG="json_serializable"
      dart: stable
    - stage: unit_test
      name: "SDK: 2.0.0 - DIR: json_serializable - TASKS: pub run test --run-skipped test/ensure_build_test.dart"
      script: ./tool/travis.sh test_2
      env: PKG="json_serializable"
      dart: "2.0.0"
    - stage: unit_test
      name: "SDK: dev - DIR: json_serializable - TASKS: pub run test --run-skipped test/ensure_build_test.dart"
      script: ./tool/travis.sh test_2
      env: PKG="json_serializable"
      dart: dev
    - stage: unit_test
      name: "SDK: stable - DIR: json_serializable - TASKS: pub run build_runner test -- -p chrome"
      script: ./tool/travis.sh command
      env: PKG="json_serializable"
      dart: stable
    - stage: unit_test
      name: "SDK: 2.0.0 - DIR: json_serializable - TASKS: pub run build_runner test -- -p chrome"
      script: ./tool/travis.sh command
      env: PKG="json_serializable"
      dart: "2.0.0"
    - stage: unit_test
      name: "SDK: dev - DIR: json_serializable - TASKS: pub run build_runner test -- -p chrome"
      script: ./tool/travis.sh command
      env: PKG="json_serializable"
      dart: dev

stages:
  - analyzer_and_format
  - analyzer_and_format_stable
  - unit_test

cache:
  directories:
    - "$HOME/.pub-cache"
    - example/.dart_tool/build
    - json_serializable/.dart_tool/build
