# Created with https://github.com/dart-lang/mono_repo
language: dart

####################
# Begin hand edits #
####################
sudo: required
addons:
  chrome: stable
##################
# End hand edits #
##################

jobs:
  include:
    - stage: analyzer_and_format
      name: "SDK: dev - DIR: example - TASKS: dartfmt -n --set-exit-if-changed ."
      script: ./tool/travis.sh dartfmt
      env: PKG="example"
      dart: dev
    - stage: analyzer_and_format
      name: "SDK: dev - DIR: example - TASKS: dartanalyzer --fatal-infos --fatal-warnings ."
      script: ./tool/travis.sh dartanalyzer
      env: PKG="example"
      dart: dev
    - stage: unit_test
      name: "SDK: dev - DIR: example - TASKS: pub run test --run-skipped"
      script: ./tool/travis.sh test_0
      env: PKG="example"
      dart: dev
    - stage: analyzer_and_format
      name: "SDK: dev - DIR: json_annotation - TASKS: dartfmt -n --set-exit-if-changed ."
      script: ./tool/travis.sh dartfmt
      env: PKG="json_annotation"
      dart: dev
    - stage: analyzer_and_format
      name: "SDK: dev - DIR: json_annotation - TASKS: dartanalyzer --fatal-infos --fatal-warnings ."
      script: ./tool/travis.sh dartanalyzer
      env: PKG="json_annotation"
      dart: dev
    - stage: analyzer_and_format
      name: "SDK: dev - DIR: json_serializable - TASKS: dartfmt -n --set-exit-if-changed ."
      script: ./tool/travis.sh dartfmt
      env: PKG="json_serializable"
      dart: dev
    - stage: analyzer_and_format
      name: "SDK: dev - DIR: json_serializable - TASKS: dartanalyzer --fatal-infos --fatal-warnings ."
      script: ./tool/travis.sh dartanalyzer
      env: PKG="json_serializable"
      dart: dev
    - stage: unit_test
      name: "SDK: dev - DIR: json_serializable - TASKS: pub run test"
      script: ./tool/travis.sh test_1
      env: PKG="json_serializable"
      dart: dev
    - stage: unit_test
      name: "SDK: dev - DIR: json_serializable - TASKS: pub run test --run-skipped test/ensure_build_test.dart"
      script: ./tool/travis.sh test_2
      env: PKG="json_serializable"
      dart: dev
    - stage: unit_test
      name: "SDK: dev - DIR: json_serializable - TASKS: pub run build_runner test -- -p chrome"
      script: ./tool/travis.sh command
      env: PKG="json_serializable"
      dart: dev

stages:
  - analyzer_and_format
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master,0_5_x]

cache:
  directories:
    - $HOME/.pub-cache
    - json_serializable/.dart_tool/build
