# Created with https://github.com/dart-lang/mono_repo
language: dart

dart:
  - dev
  - stable

env:
  - PKG=example TASK=dartanalyzer_1
  - PKG=example TASK=dartfmt
  - PKG=example TASK=test
  - PKG=json_annotation TASK=dartanalyzer_1
  - PKG=json_annotation TASK=dartfmt
  - PKG=json_serializable TASK=dartanalyzer_0
  - PKG=json_serializable TASK=dartanalyzer_1
  - PKG=json_serializable TASK=dartfmt
  - PKG=json_serializable TASK=test

matrix:
  exclude:
    - dart: stable
      env: PKG=example TASK=dartanalyzer_1
    - dart: stable
      env: PKG=example TASK=dartfmt
    - dart: stable
      env: PKG=json_serializable TASK=dartanalyzer_0
    - dart: stable
      env: PKG=json_serializable TASK=dartanalyzer_1
    - dart: stable
      env: PKG=json_serializable TASK=dartfmt
    - dart: stable
      env: PKG=json_serializable TASK=test

script: ./tool/travis.sh

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
