language: dart
sudo: false
dart:
  - dev
  - stable
dart_task:
  # Run the tests -- include the default-skipped presubmit tests
  - test: --run-skipped
    xvfb: false
  - dartfmt
  - dartanalyzer

matrix:
  exclude:
    dart: stable
    dart_task:
      - test: --run-skipped
        xvfb: false
  include:
    dart: 1.23.0
    dart_task:
      - test: --run-skipped
        xvfb: false


# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
