name: json_serializable
version: 0.2.1
author: Dart Team <misc@dartlang.org>
description: Generates utilities to aid in serializing to/from JSON.
homepage: https://github.com/dart-lang/json_serializable
environment:
  sdk: '>=1.24.0 <2.0.0-dev.infinity'
dependencies:
  analyzer: '>=0.29.10 <0.31.0'
  build: ^0.9.0
  cli_util: ^0.1.0
  path: ^1.3.2
  source_gen: ^0.7.0
dev_dependencies:
  build_runner: ^0.3.2
  build_test: ^0.6.0
  collection: ^1.14.0
  test: ^0.12.3
