name: yaml_decode
version: 0.1.0-dev
author: Dart Team <misc@dartlang.org>
description: >-
  Utilities for generating helpful error messages when decoding YAML documents
  using package:json_serializable and package:yaml.
homepage: https://github.com/dart-lang/json_serializable
environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  json_annotation: ^2.2.0
  yaml: ^2.1.13

dev_dependencies:
  test: ^1.6.0
