# See https://github.com/google/mono_repo.dart for details on this file
dart:
- beta # change this to 1.12.0 when it's released!
- dev

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos .
