# See https://github.com/dart-lang/mono_repo for details
dart:
- 2.1.0
- dev

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings --fatal-infos .
    dart: [dev]
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings .
    dart: [2.1.0]


