# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - analyzer_and_format_stable:
      - group:
          - dartfmt
          - dartanalyzer: --fatal-warnings .
        dart: [stable]
