# See https://github.com/dart-lang/mono_repo for details
dart:
- dev
- 2.0.0

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings --fatal-infos .
    dart: [dev]
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings .
    dart: [2.0.0]


