name: json_annotation
version: 0.2.7+1
description: >-
  Classes and helper functions that support JSON code generation via the
  `json_serializable` package.
homepage: https://github.com/dart-lang/json_serializable
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.0.0-dev.54.0 <2.0.0'
