# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev

stages:
  - analyzer_and_format:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
  - unit_test:
    # Run the tests -- include the default-skipped presubmit tests
    - test
    - test: --run-skipped test/ensure_build_test.dart
    - command: pub run build_runner test -- -p chrome
