language: dart

# Unpin SDK after https://github.com/dart-lang/sdk/issues/31940
dart:
  - "dev/release/2.0.0-dev.17.0"
  - stable

dart_task:
  # Run the tests -- include the default-skipped presubmit tests
  - test: --run-skipped

matrix:
  include:
    - dart: "dev/release/2.0.0-dev.17.0"
      dart_task:
        dartfmt: sdk
    - dart: "dev/release/2.0.0-dev.17.0"
      dart_task: dartanalyzer

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
