targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - test/default_value/**
          - test/generic_files/*_test.dart
          - test/integration/*_test.dart
          - test/kitchen_sink/**

# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  json_serializable:
    import: "package:json_serializable/builder.dart"
    builder_factories: ["jsonSerializable"]
    build_extensions: {".dart": ["json_serializable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
