targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - test/default_value/**
          - test/json_serializable_integration*
          - test/kitchen_sink/**

# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  json_serializable:
    import: "package:json_serializable/builder.dart"
    builder_factories: ["jsonSerializable"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
