builders:
  json_serializable:
    target: ":json_serializable"
    import: "package:json_serializable/builder.dart"
    builder_factories: ["jsonSerializable"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
