# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  json_serializable:
    import: "package:json_serializable/builder.dart"
    builder_factories: ["jsonSerializable"]
    auto_apply: dependents
    build_to: source
