# See https://github.com/dart-lang/mono_repo for details
dart:
- 2.0.0
- dev

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
    dart: [dev]
- analyzer_and_format_2_0:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings .
    dart: [2.0.0]
- unit_test:
  # Run the tests -- include the default-skipped presubmit tests
  - test
  - test: --run-skipped test/ensure_build_test.dart
  - command: pub run build_runner test -- -p chrome

cache:
  directories:
  - .dart_tool/build
