name: json_serializable
version: 0.3.1+1
author: Dart Team <misc@dartlang.org>
description: Generates utilities to aid in serializing to/from JSON.
homepage: https://github.com/dart-lang/json_serializable
environment:
  sdk: '>=2.0.0-dev <2.0.0'
dependencies:
  analyzer: '>=0.29.10 <0.31.0'
  build: '>=0.9.0 <0.13.0'
  build_config: ^0.2.1
  cli_util: ^0.1.0

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation`. Properly constrains all features it provides.
  json_annotation: '>=0.2.2 <0.2.3'
  path: ^1.3.2
  source_gen: ^0.7.1
dev_dependencies:
  build_runner: ^0.7.0
  build_test: ">=0.9.0 <0.11.0"
  collection: ^1.14.0
  dart_style: ^1.0.0
  test: ^0.12.3
