# See https://github.com/dart-lang/mono_repo for details
dart:
- stable

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings --fatal-infos .
  - group:
    - dartanalyzer: --fatal-warnings .
- unit_test:
  - test
- ensure_build:
  - test: --run-skipped -t presubmit-only test/ensure_build_test.dart

cache:
  directories:
  - .dart_tool
